let itemData = [
  {
    id: "jklmn",
    source: "./Sale-Items/shoes/nike-shoe-2.png",
    name: "Nike Red and Black Air Max",
    discountPrice: 50,
    actualPrice: 75,
  },
  {
    id: "mvnfw",
    source: "./Sale-Items/shoes/nike-shoe-3.png",
    name: "Nike Air Max 90 Essential Id Men's Shoe",
    discountPrice: 87,
    actualPrice: 100,
  },
  {
    id: "qersz",
    source: "./Sale-Items/shoes/nike-shoe-4.png",
    name: "Nike Jordan 4 Retro Toro Bravo",
    discountPrice: 135,
    actualPrice: 150,
  },
  {
    id: "afopu",
    source: "./Sale-Items/shoes/nike-shoe-5.png",
    name: "Nike Air Jordan 1, Virgil A",
    discountPrice: 200,
    actualPrice: 230,
  },
  {
    id: "trtos",
    source: "./Sale-Items/shoes/nike-shoe-6.png",
    name: "Nike The Classic Jumpman Logo Sits",
    discountPrice: 225,
    actualPrice: 250,
  },
  {
    id: "vmsfl",
    source: "./Sale-Items/shoes/nike-shoe-7.png",
    name: "Nike Shoes Lunarglide 6 Running Shoes",
    discountPrice: 320,
    actualPrice: 350,
  },
  {
    id: "soprf",
    source: "./Sale-Items/clothes/clothes-1.png",
    name: "Rrl - Mitchell And Ness All Over Shirt",
    discountPrice: 120,
    actualPrice: 140,
  },
  {
    id: "werof",
    source: "./Sale-Items/clothes/clothes-2.png",
    name: "Mitchell & Ness Nba  Philadelphia 76ers  T-shirt",
    discountPrice: 155,
    actualPrice: 170,
  },
  {
    id: "wrsnq",
    source: "./Sale-Items/clothes/clothes-3.png",
    name: "Pink Beautiful Trauma Tour Denim Jacket",
    discountPrice: 350,
    actualPrice: 385,
  },
  {
    id: "qmlop",
    source: "./Sale-Items/clothes/clothes-4.png",
    name: "John Doe- Kevlar Leather Jacket",
    discountPrice: 450,
    actualPrice: 485,
  },
  {
    id: "sfmzp",
    source: "./Sale-Items/clothes/clothes-5.png",
    name: "Occupy Mars Shirt T-shirt",
    discountPrice: 120,
    actualPrice: 140,
  },

  {
    id: "afmrp",
    source: "./Sale-Items/clothes/clothes-6.png",
    name: "Donate To Get Swag - Occupy Mars Shirt",
    discountPrice: 115,
    actualPrice: 130,
  },
];
